### ISSUE TITLE
中文乱码 (unidentifiable Chinese code garbled Chinese character)

### ISSUE THREAD

**Issue by dingdaoyi** [jasync-sql/jasync-sql#133]
在这个例子中 https://github.com/hantsy/spring-reactive-sample 中文添加乱码

数据库配置
    @Override
    public ConnectionFactory connectionFactory() {
        String url = "mysql://root:123456@192.168.2.84:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=UTC";
        return new JasyncConnectionFactory(
            new MySQLConnectionFactory(
                URLParser.INSTANCE.parseOrDie(url, StandardCharsets.UTF_8)
            )
        );
    }

**Comment by oshai** [comment]
Can you give more details on the issue?

**Comment by dingdaoyi** [comment]
url :http://127.0.0.1:8044/posts

request:
{
	"title":"中国",
	"content":"bbb"
}


response:
{
    "timestamp": "2019-07-05T09:20:13.763+0000",
    "path": "/posts",
    "status": 500,
    "error": "Internal Server Error",
    "message": "executeMany; uncategorized R2dbcException for SQL [INSERT INTO posts (title, content) VALUES (?, ?)]; Incorrect string value: '\\xE4\\xB8\\xAD\\xE5\\x9B\\xBD' for column 'title' at row 1; nested exception is com.github.jasync.r2dbc.mysql.JasyncDatabaseException: [1366] [#HY000] Incorrect string value: '\\xE4\\xB8\\xAD\\xE5\\x9B\\xBD' for column 'title' at row 1",
    "requestId": "645fef75"
}

error message:

org.springframework.data.r2dbc.UncategorizedR2dbcException: executeMany; uncategorized R2dbcException for SQL [INSERT INTO posts (title, content) VALUES (?, ?)]; Incorrect string value: '\xE4\xB8\xAD\xE5\x9B\xBD' for column 'title' at row 1; nested exception is com.github.jasync.r2dbc.mysql.JasyncDatabaseException: [1366] [#HY000] Incorrect string value: '\xE4\xB8\xAD\xE5\x9B\xBD' for column 'title' at row 1

**Comment by oshai** [comment]
It looks like this is not a valid UTF-8 from checking online [here](https://onlineutf8tools.com/validate-utf8):

![image](https://user-images.githubusercontent.com/2683969/60767685-d8ed2d80-a0c3-11e9-9f32-afb19e74a3db.png)

I think if you're using a different encoding the solution is to configure it as well.

**Comment by dingdaoyi** [comment]
The same config in postgresql run success ,I think the problem at jasync-sql

https://github.com/hantsy/spring-reactive-sample/tree/master/boot-data-r2dbc

**Comment by mirromutth** [comment]
Ok, relax, let us discuss this issue calmly and not blame.

Yes indeed, it is UTF-8 string "中国" (the word 'China' in Chinese), unit test like following:

```Kotlin
val bytes = byteArrayOf(0xE4.toByte(), 0xB8.toByte(), 0xAD.toByte(), 0xE5.toByte(), 0x9B.toByte(), 0xBD.toByte())
assertEquals(bytes.toString(Charsets.UTF_8), "中国")
```

But first, we should make sure the table, `posts`, has encoded by `utf8_*` or `utf8mb4_*`.

@dingdaoyi Try execute following SQL on your MySQL official client to get more informations:

```SQL
SELECT `TABLE_SCHEMA`, `TABLE_NAME`, `TABLE_COLLATION`
FROM `INFORMATION_SCHEMA`.`TABLES`
WHERE `TABLE_NAME` = 'posts' AND `TABLE_SCHEMA` = 'test';
```

The field `TABLE_COLLATION` should be a string which starts with "utf8", like `utf8_unicode_ci`, `utf8mb4_general_ci`, etc.

If `TABLE_COLLATION` is not starts with "utf8", try change the collation in database/table definitions.

If the problem is still exists, should execute `SELECT @@collation_connection` in `jasync-sql` to get current character collation of the connection, it should also be a string which starts with "utf8".

If it is not starts with "utf8", should change the `charset` of `com.github.jasync.sql.db.Configuration` to `StandardCharsets.UTF_8` before create a jasync connection.

If both are start with "utf8", @oshai we should build a MySQL environment same as @dingdaoyi for test the unit of `StringEncoder`.

**Comment by oshai** [comment]
I am closing it due to inactivity
