### ISSUE TITLE
poor speed

### ISSUE THREAD

**Issue by sysmat** [jasync-sql/jasync-sql#181]
It is a great lib but speed is poor, the same query is 15 times slower then with  mysql-connector-java

Regards, Tomaž

**Comment by oshai** [comment]
Can you give more details about how exactly it is being tested. Do you see anything that can be improved. Note that there are cases that jasync works best, and that should be when there are many concurrent active connections. In such cases it will save cost of context switches between threads. Of course there are also cases that jdbc will work better.

**Comment by sysmat** [comment]
Mysql ver: '5.5.62-38.14'

```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.48</version>
 </dependency>
private static Collection<Org> getOrgsOk(Connection con) {
        Long startTime = Instant.now().toEpochMilli();
        Collection<Org> result = new ArrayList<>();
        String sql = "SELECT id, name FROM organization WHERE status='ok'";
        try {
            Statement st = con.createStatement();
            ResultSet resultRS = st.executeQuery(sql);

            while (resultRS.next()) {
                Org org = new Org();
                org.id = resultRS.getInt(1);
                org.name = resultRS.getString(2);
                result.add(org);
            }

        } catch (SQLException e) {
            System.out.println("getOrgsOk: SQLException=" + Routines.exception2String(e));
        }

        long endTime = Instant.now().toEpochMilli();
        long timeElapsed = endTime - startTime;
        System.out.println("getOrgsOk:Execution time in milliseconds: " + timeElapsed);

        return result;
    }

```

```
<dependency>
            <groupId>com.github.jasync-sql</groupId>
            <artifactId>jasync-mysql</artifactId>
            <version>1.0.14</version>
        </dependency>

public Collection<Org> getOrgsOk() {
        Long startTime = Instant.now().toEpochMilli();
        Collection<Org> result = new ArrayList<>();
        String sql = "SELECT id, name FROM organization WHERE status='ok'";
        try {
            con.sendQuery(sql)
               .get()
               .getRows()
               .forEach(row ->{
                    Org org = new Org();
                    org.id = row.getInt(0);
                    org.name = row.getString(1);
                    result.add(org);
                });

        } catch (InterruptedException | ExecutionException ex) {
            System.out.println("getOrgsOk: SQLException=" + Routines.exception2String(ex));
        }

        long endTime = Instant.now().toEpochMilli();
        long timeElapsed = endTime - startTime;
        System.out.println("getOrgsOk:Execution time in milliseconds: " + timeElapsed);
        return result;
    }


```

**Comment by oshai** [comment]
@sysmat comparing drivers like that feels like comparing apples and oranges, but I will try to give some comments:
- when comparing and measuring performance it's better to use jmh to get accurate results.
- you haven't published any measured results other than saying "the same query is 15 times slower"
- is the database on the same host? another host? what is the latency to it? I am asking because in most real world scenario driver has small effect on performance because network and disk io are part of the game.
- and maybe the most important note: comparing jasync by calling con.sendQuery(sql).get() is just not how this library is intended to work. Async/Reactive libs will work fine on scenarios where you have many concurrent requests to your service. In traditional services you'll have many threads while in the async model you have threads as the number of cores or so. So you can gain in context switches, cpu cycles etc'

Hope that helps,
Ohad.

**Comment by sysmat** [comment]
* It's not real benchmark, it was simple batch program, I didn't use parallel streams, treads switching ...
* mysql is on different host  
* Async: 603 ms Sync: 46 ms

**Comment by oshai** [comment]
ok, can you please check with a profiler what method is "wasting" the time?
