### ISSUE TITLE
Support for exporting metics?

### ISSUE THREAD

**Issue by arhont375** [jasync-sql/jasync-sql#211]
Hello, it looks like a nice library that consider to use.
But for usage in many production applications it's required to monitor state of connection pool / execution of statements.
As far as I checked I cann't find any support for exporting metrics (eg Prometheus), did I miss some wiki page with examples?
Or maybe it's planned?

**Comment by oshai** [comment]
Yes, metrics are part of the usage.
Since we don't want to couple to a specific metrics framework we provide the following capabilities:
* [interceptors](https://github.com/jasync-sql/jasync-sql/wiki/Interceptors) allows measuring each query time and reporting it by plugging into the query (it also allows modifying the query but here it's not needed) - see example [here](https://github.com/jasync-sql/jasync-sql/blob/9c6fa7cd145483ebd74beb4bd1f0707542c8e9c9/db-async-common/src/main/java/com/github/jasync/sql/db/interceptor/Interceptors.kt).
* ConnectionPool object contains [properties](https://github.com/jasync-sql/jasync-sql/blob/9c6fa7cd14/db-async-common/src/main/java/com/github/jasync/sql/db/pool/ConnectionPool.kt#L118) that can be inspected:
  * inUseConnectionsCount
  * futuresWaitingForConnectionCount
  * idleConnectionsCount

Let me know if that is clear enough or if something is missing.

**Comment by arhont375** [comment]
Thanks you for quick response.
Yes, I think Interceptors provide ways to configure metrics by ourselves, though integration with some open standard as Micrometer may make usage of library more convenient.
